Feature: customizable shell command
manateelazycat/sdcv pull request #26
Opened 2021-08-02 11:16 UTC by xFA25E

This is the first version of custamizable shell command with a list.

@pRot0ta1p @sirikid

2021-08-02 13:50 UTC, sirikid requested changes

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +You can customize this value with local dir,then you don't need copy dict data
Missing space after comma

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +(with-no-warnings
What kinds of warnings you want to suppress?

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +		(beginning-of-line nil)
Tabs

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +				 (<= char-offset (+ search-index (length word))))
Tabs again

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +				 (<= char-offset (+ search-index (length word))))
You can use single `<=` here

2021-08-02 13:50 UTC, sirikid commented on sdcv.el
> +	(ignore-errors
Tabs

2021-08-02 16:58 UTC, xFA25E commented
Thanks for the review!

2021-08-02 18:17 UTC, sirikid approved these changes

2021-08-03 02:29 UTC, pRot0ta1p approved these changes
Looks good to me

2021-08-07 14:16 UTC, manateelazycat commented
First, thanks for patch.

Please split the patch, each patch only do one thing, all the content is mixed together, I can't review.

I don't understand what is the purpose of custom shell command?

2021-08-09 10:31 UTC, xFA25E commented
The purpose is to make sdcv shell command customizable

2021-08-09 10:34 UTC, xFA25E commented
You are right, I should split the patch. I'll send a splitted version soon

2021-12-10 14:47 UTC, closed without merging